### ISSUE TITLE
Domains on datastudio links all seem to start with 0 or 1

### ISSUE THREAD

**Issue by bluesmoon** [anniesullie/LCP_Examples#4]
This is more of a question than an issue. I've noticed that the datastudio dashboards linked from the README only include domains that start with a 0 or a 1 (eg: 101chords.blogspot.com or 012grp.co.jp). I was wondering if this was due to a sort ordering, and how we might be able to change this to use most popular domains instead.

Thanks.

**Comment by anniesullie** [comment]
It is due to ordering. The scatter plots can't show all the points at once. I can switch the ordering to be reverse alphabetical instead, but of course that doesn't help much. Do you know of a public bigquery table that ranks domains by popularity I could join the data with?

I've made the bigquery tables that I used to generate the graphs public if it helps:
`lcp-analysis.HttpArchive_PerformanceMetrics.PerformanceMetrics_2019_10_01_Desktop`
`lcp-analysis.HttpArchive_PerformanceMetrics.PerformanceMetrics_2019_10_01` (mobile)

**Comment by bluesmoon** [comment]
I think Rick Viscomi has a solution here: https://discuss.httparchive.org/t/getting-domain-rank-with-the-new-rank-less-chrome-ux-report-corpus/1444

There's also the option of using the tranco list: https://tranco-list.eu/

**Comment by anniesullie** [comment]
Thanks! I used Rick's method to sort by rank; mobile and desktop charts are updated.

**Comment by bluesmoon** [comment]
Thanks.
